import React from 'react';
import { ScrollView, StyleSheet, Text, View, ActivityIndicator } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Colors, Typography, Spacing, BorderRadius } from '@/constants/theme';
import Card from '@/components/Card';
import ScreenWrapper from '@/components/ScreenWrapper';
import { gitaApi, Chapter } from '@/services/gitaApi';

function getDayKey(): number {
    const now = new Date();
    const utcMidnight = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
    return Math.floor(utcMidnight / 86400000);
}

export default function WisdomScreen() {
    const router = useRouter();
    const [chapters, setChapters] = React.useState<Chapter[]>([]);
    const [loading, setLoading] = React.useState(true);

    React.useEffect(() => {
        const loadChapters = async () => {
            try {
                const data = await gitaApi.getChapters();
                setChapters(data);
            } catch (error) {
                console.error('Failed to load chapters:', error);
            } finally {
                setLoading(false);
            }
        };

        loadChapters();
    }, []);

    const todaysChapterId = React.useMemo(() => {
        if (chapters.length === 0) return 2;
        const dayIndex = getDayKey() % chapters.length;
        return chapters[dayIndex]?.chapter_number || 2;
    }, [chapters]);

    const topics = [
        {
            id: 'dharma',
            title: 'Dharma',
            subtitle: 'Duty & Cosmic Order',
            description: 'The eternal law that sustains the universe and the individual.',
        },
        {
            id: 'tapas',
            title: 'Tapas',
            subtitle: 'Self-Discipline',
            description: 'The heat generated by spiritual practice that burns away impurities.',
        },
        {
            id: 'indriya',
            title: 'Indriya Nigraha',
            subtitle: 'Sense Control',
            description: 'Mastery over the senses to prevent the mind from being led astray.',
        },
    ];

    if (loading) {
      return (
        <ScreenWrapper style={styles.centered}>
          <ActivityIndicator size="large" color={Colors.primary} />
        </ScreenWrapper>
      );
    }

    return (
        <ScreenWrapper>
            <ScrollView
                showsVerticalScrollIndicator={false}
                contentContainerStyle={styles.scrollContent}
            >
                <Text style={styles.headerTitle}>Wisdom</Text>

                <Card
                    title="Today's Teaching"
                    onPress={() =>
                        router.push({
                            pathname: '/gita-reading',
                            params: { chapter: todaysChapterId.toString() },
                        })
                    }
                    style={styles.featuredCard}
                >
                    <View style={styles.featuredContent}>
                        <Ionicons name="sparkles-outline" size={24} color={Colors.primary} />
                        <View style={styles.featuredText}>
                            <Text style={styles.featuredTitle}>Bhagavad Gita, Ch. {todaysChapterId}</Text>
                            <Text style={styles.featuredSubtitle}>Read with AI Guide</Text>
                        </View>
                        <Ionicons name="chevron-forward" size={20} color={Colors.textMuted} />
                    </View>
                </Card>

                <Text style={styles.sectionTitle}>Key Concepts</Text>

                <Card
                    title="Read Full Bhagavad Gita"
                    subtitle="Browse all 18 Chapters"
                    onPress={() => router.push('/wisdom-chapters')} // I'll create this or use existing list logic
                    style={styles.libraryCard}
                >
                    <View style={styles.libraryFooter}>
                        <Ionicons name="library-outline" size={24} color={Colors.primary} />
                    </View>
                </Card>

                {topics.map((topic) => (
                    <Card key={topic.id} style={styles.topicCard}>
                        <Text style={styles.topicTitle}>{topic.title}</Text>
                        <Text style={styles.topicSubtitle}>{topic.subtitle}</Text>
                        <Text style={styles.topicDesc}>{topic.description}</Text>
                    </Card>
                ))}
                
                <View style={styles.bottomPadding} />
            </ScrollView>
        </ScreenWrapper>
    );
}

const styles = StyleSheet.create({
    scrollContent: {
        padding: 24,
        paddingBottom: 40,
    },
    centered: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: Colors.textLight,
        marginBottom: 24,
        marginTop: 8,
        fontFamily: Typography.serif.join(','),
    },
    featuredCard: {
        borderColor: Colors.primary,
        borderWidth: 1,
        marginBottom: 24,
    },
    featuredContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    featuredText: {
        marginLeft: 16,
        flex: 1,
    },
    featuredTitle: {
        color: Colors.textLight,
        fontSize: 16,
        fontWeight: '600',
    },
    featuredSubtitle: {
        color: Colors.textMuted,
        fontSize: 14,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: Colors.textLight,
        marginBottom: 16,
        fontFamily: Typography.serif.join(','),
    },
    libraryCard: {
        borderColor: Colors.borderLight,
    },
    libraryFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    topicCard: {
        paddingVertical: 16,
    },
    topicTitle: {
        fontSize: 22,
        fontFamily: Typography.serif.join(','),
        color: Colors.primary,
        marginBottom: 4,
    },
    topicSubtitle: {
        fontSize: 14,
        fontWeight: '700',
        color: Colors.textLight,
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    topicDesc: {
        fontSize: 14,
        color: Colors.textMuted,
        lineHeight: 22,
    },
    bottomPadding: {
      height: 40,
    }
});

